-- Seed data for products table
INSERT INTO products (name, description, category, price, quantity) VALUES
-- Electronics (20 products)
('Ultra HD Smart TV 55"', '4K resolution with HDR and smart features', 'Electronics', 899.99, 25),
('Wireless Noise-Cancelling Headphones', 'Premium sound quality with 30-hour battery life', 'Electronics', 299.99, 50),
('Gaming Laptop Pro', 'High-performance gaming laptop with RTX 3080', 'Electronics', 1999.99, 15),
('Smart Watch Series 5', 'Fitness tracking and notifications', 'Electronics', 249.99, 40),
('Bluetooth Speaker', 'Portable waterproof speaker with deep bass', 'Electronics', 79.99, 60),
('Wireless Earbuds', 'True wireless earbuds with charging case', 'Electronics', 129.99, 75),
('Tablet Pro 12"', 'Professional tablet with stylus support', 'Electronics', 799.99, 30),
('Smart Home Hub', 'Control your smart home devices', 'Electronics', 149.99, 45),
('External SSD 1TB', 'Ultra-fast portable storage', 'Electronics', 159.99, 100),
('Mechanical Keyboard', 'RGB mechanical gaming keyboard', 'Electronics', 129.99, 55),
('Gaming Mouse', 'High-precision gaming mouse with RGB', 'Electronics', 69.99, 80),
('Webcam 4K', 'Ultra HD webcam with noise cancellation', 'Electronics', 199.99, 35),
('Wireless Router', 'High-speed WiFi 6 router', 'Electronics', 179.99, 40),
('Power Bank 20000mAh', 'Fast charging portable battery', 'Electronics', 49.99, 90),
('Smart Doorbell', 'Video doorbell with motion detection', 'Electronics', 199.99, 30),
('Smart Light Bulb Set', 'Color-changing smart bulbs, pack of 4', 'Electronics', 59.99, 70),
('Wireless Charging Pad', 'Fast wireless charger for smartphones', 'Electronics', 39.99, 85),
('USB-C Hub', 'Multi-port adapter for laptops', 'Electronics', 49.99, 95),
('Smart Scale', 'WiFi connected body composition scale', 'Electronics', 89.99, 45),
('Fitness Tracker', 'Water-resistant activity tracker', 'Electronics', 79.99, 65),

-- Furniture (20 products)
('Ergonomic Office Chair', 'Adjustable lumbar support office chair', 'Furniture', 299.99, 20),
('Standing Desk', 'Electric height-adjustable desk', 'Furniture', 399.99, 15),
('Bookshelf', 'Modern 5-shelf bookcase', 'Furniture', 149.99, 30),
('Coffee Table', 'Glass top coffee table with storage', 'Furniture', 199.99, 25),
('Dining Table Set', '6-person dining table with chairs', 'Furniture', 899.99, 10),
('Sofa Bed', 'Convertible sofa with memory foam mattress', 'Furniture', 699.99, 12),
('TV Stand', 'Modern entertainment center', 'Furniture', 249.99, 18),
('Bar Stools Set', 'Set of 4 modern bar stools', 'Furniture', 299.99, 15),
('Console Table', 'Narrow entryway console table', 'Furniture', 179.99, 22),
('Accent Chair', 'Modern accent chair with ottoman', 'Furniture', 349.99, 15),
('Wardrobe', 'Large wooden wardrobe with mirror', 'Furniture', 499.99, 12),
('Nightstand', 'Bedside table with drawer', 'Furniture', 129.99, 25),
('Dresser', '6-drawer wooden dresser', 'Furniture', 399.99, 15),
('Desk Lamp', 'Adjustable LED desk lamp', 'Furniture', 49.99, 40),
('Floor Lamp', 'Modern arc floor lamp', 'Furniture', 129.99, 20),
('Side Table', 'Nesting side tables set of 2', 'Furniture', 159.99, 25),
('Bench', 'Upholstered entryway bench', 'Furniture', 199.99, 18),
('Shelving Unit', 'Modular wall shelving system', 'Furniture', 179.99, 22),
('Ottoman', 'Storage ottoman with tray top', 'Furniture', 149.99, 25),
('Plant Stand', 'Tiered plant stand with 3 levels', 'Furniture', 79.99, 30),

-- Kitchen & Appliances (20 products)
('Smart Refrigerator', 'WiFi-enabled refrigerator with touchscreen', 'Appliances', 2499.99, 8),
('Dishwasher', 'Energy-efficient dishwasher', 'Appliances', 699.99, 15),
('Microwave Oven', 'Convection microwave with sensor cooking', 'Appliances', 199.99, 25),
('Coffee Maker', 'Programmable coffee maker with thermal carafe', 'Appliances', 89.99, 35),
('Blender', 'High-speed blender with multiple settings', 'Appliances', 79.99, 40),
('Food Processor', 'Multi-purpose food processor', 'Appliances', 149.99, 20),
('Toaster Oven', 'Convection toaster oven with air fry', 'Appliances', 129.99, 30),
('Stand Mixer', 'Professional stand mixer with attachments', 'Appliances', 399.99, 15),
('Electric Kettle', 'Temperature control electric kettle', 'Appliances', 59.99, 45),
('Rice Cooker', 'Fuzzy logic rice cooker', 'Appliances', 69.99, 35),
('Slow Cooker', 'Programmable slow cooker', 'Appliances', 49.99, 40),
('Air Fryer', 'Digital air fryer with multiple functions', 'Appliances', 119.99, 30),
('Hand Mixer', '5-speed hand mixer with attachments', 'Appliances', 39.99, 50),
('Immersion Blender', 'Stick blender with chopper attachment', 'Appliances', 49.99, 40),
('Waffle Maker', 'Belgian waffle maker with temperature control', 'Appliances', 59.99, 35),
('Electric Griddle', 'Large electric griddle with temperature control', 'Appliances', 79.99, 25),
('Bread Maker', 'Automatic bread maker with multiple settings', 'Appliances', 129.99, 20),
('Juicer', 'Cold press juicer', 'Appliances', 199.99, 15),
('Electric Can Opener', 'Automatic can opener with bottle opener', 'Appliances', 24.99, 60),
('Wine Cooler', '12-bottle thermoelectric wine cooler', 'Appliances', 199.99, 20),

-- Sports & Outdoors (20 products)
('Mountain Bike', '21-speed mountain bike with disc brakes', 'Sports', 499.99, 15),
('Treadmill', 'Folding treadmill with LCD display', 'Sports', 799.99, 10),
('Yoga Mat', 'Extra thick non-slip yoga mat', 'Sports', 29.99, 100),
('Dumbbell Set', 'Adjustable dumbbell set 5-50 lbs', 'Sports', 299.99, 20),
('Tennis Racket', 'Professional tennis racket with cover', 'Sports', 89.99, 40),
('Basketball', 'Official size basketball', 'Sports', 24.99, 80),
('Camping Tent', '4-person waterproof camping tent', 'Sports', 199.99, 25),
('Sleeping Bag', 'Cold weather sleeping bag', 'Sports', 79.99, 35),
('Hiking Boots', 'Waterproof hiking boots', 'Sports', 129.99, 30),
('Fishing Rod', 'Spinning fishing rod and reel combo', 'Sports', 69.99, 45),
('Swimming Goggles', 'Anti-fog swimming goggles', 'Sports', 19.99, 100),
('Jump Rope', 'Weighted jump rope with bearings', 'Sports', 14.99, 120),
('Resistance Bands', 'Set of 5 resistance bands', 'Sports', 24.99, 90),
('Foam Roller', 'High-density foam roller', 'Sports', 29.99, 70),
('Sports Watch', 'GPS sports watch with heart rate monitor', 'Sports', 199.99, 25),
('Yoga Block Set', 'Set of 4 yoga blocks', 'Sports', 19.99, 85),
('Exercise Ball', 'Anti-burst exercise ball', 'Sports', 24.99, 60),
('Kettlebell', 'Cast iron kettlebell 20 lbs', 'Sports', 39.99, 50),
('Pull-up Bar', 'Doorway pull-up bar', 'Sports', 29.99, 75),
('Balance Board', 'Wooden balance board', 'Sports', 49.99, 40),

-- Home & Garden (20 products)
('Robot Vacuum', 'Smart robot vacuum with app control', 'Home', 299.99, 20),
('Air Purifier', 'HEPA air purifier for large rooms', 'Home', 199.99, 25),
('Humidifier', 'Ultrasonic cool mist humidifier', 'Home', 49.99, 40),
('Smart Thermostat', 'WiFi-enabled smart thermostat', 'Home', 249.99, 30),
('Security Camera', 'Wireless security camera with night vision', 'Home', 89.99, 35),
('Smart Lock', 'Fingerprint smart door lock', 'Home', 199.99, 25),
('Garden Tool Set', '12-piece garden tool set', 'Garden', 79.99, 30),
('Plant Mister', 'Fine mist sprayer for plants', 'Garden', 9.99, 100),
('Garden Hose', '50ft expandable garden hose', 'Garden', 39.99, 45),
('Pruning Shears', 'Professional pruning shears', 'Garden', 24.99, 60),
('Garden Gloves', 'Leather garden gloves', 'Garden', 14.99, 80),
('Watering Can', '2-gallon watering can', 'Garden', 19.99, 55),
('Plant Food', 'Organic plant food 1lb', 'Garden', 12.99, 90),
('Garden Kneeler', 'Foldable garden kneeler and seat', 'Garden', 29.99, 40),
('Garden Cart', 'Heavy-duty garden cart', 'Garden', 89.99, 25),
('Garden Stakes', 'Set of 50 garden stakes', 'Garden', 14.99, 70),
('Garden Twine', 'Natural jute garden twine 100ft', 'Garden', 9.99, 85),
('Garden Markers', 'Set of 20 plant markers', 'Garden', 12.99, 65),
('Garden Trowel', 'Stainless steel garden trowel', 'Garden', 12.99, 75),
('Garden Apron', 'Waterproof garden apron with pockets', 'Garden', 24.99, 45); 